myhealth:
    withings:
        baseUri: https://wbsapi.withings.net/v2
        tokenFile: file:/your_withings_token_json_path/withings-token.json

withings:
    api:
        tokenHost: https://wbsapi.withings.net
        clientId: your_client_id
        clientSecret: your_client_secret
        redirectUri: your_redirect_uri
